// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlZS3G5iMHmCuj2MPLfiqdNuhmud9j4UY',
    appId: '1:706321535461:web:fb7c10fe0b0f057e8d5f0c',
    messagingSenderId: '706321535461',
    projectId: 'finbud-99269',
    authDomain: 'finbud-99269.firebaseapp.com',
    storageBucket: 'finbud-99269.appspot.com',
    measurementId: 'G-FHL3H2R40X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDE5pRKCtEhOvLL3CMIQb5iozJ2zn19yY',
    appId: '1:706321535461:android:f9a70db3fd46115b8d5f0c',
    messagingSenderId: '706321535461',
    projectId: 'finbud-99269',
    storageBucket: 'finbud-99269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcFy0gZfNh8LOJdBKEAgJl-d-1m4Ot7Lk',
    appId: '1:706321535461:ios:3410b035e4421dae8d5f0c',
    messagingSenderId: '706321535461',
    projectId: 'finbud-99269',
    storageBucket: 'finbud-99269.appspot.com',
    iosBundleId: 'com.tilakpuli.budgetAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcFy0gZfNh8LOJdBKEAgJl-d-1m4Ot7Lk',
    appId: '1:706321535461:ios:47d2dc7f69c234d88d5f0c',
    messagingSenderId: '706321535461',
    projectId: 'finbud-99269',
    storageBucket: 'finbud-99269.appspot.com',
    iosBundleId: 'com.tilakpuli.budgetAi.RunnerTests',
  );
}
